#cloud-config

package_update: true

packages:
  - jq
  - git
  - wget
  - curl
  - unzip
  - net-tools
  - python3-pip

runcmd:
  - pip3 install ansible
  - git clone -b azure --single-branch https://github.com/mrajani/hc-vault.git /home/${userlogin}/az-vaultraft

final_message: "The system is finally up, after $UPTIME seconds"
