#cloud-config

package_update: true

apt:
  preserve_sources_list: true
  primary:
    - arches: [amd64, i386, default]
  sources:
    azure-cli.list:
      source: 'deb https://packages.microsoft.com/repos/azure-cli $RELEASE main'
      keyid: BC52 8686 B50D 79E3 39D3 721C EB3E 94AD BE12 29CF
      keyserver: 'https://packages.microsoft.com/keys/microsoft.asc'

packages:
  - jq
  - git
  - wget
  - curl
  - unzip
  - net-tools
  - azure-cli
  - python3-pip

runcmd:
  - pip3 install ansible
  - git clone -b azure --single-branch https://github.com/mrajani/hc-vault.git /home/${userlogin}/az-vaultraft
  - ansible-playbook /home/${userlogin}/az-vaultraft/azure/vault-raft/vault.yml -e "@/usr/local/etc/az_keyvault_vars.yml"

final_message: "The system is finally up, after $UPTIME seconds"
