---
  - name: Get Resource Groups
    hosts: localhost
    gather_facts: no
    connection: local
    collections:
      - azure.azcollection
    vars_files:
      - vars.yml

    tasks:
      - name: Get facts for one resource group including resources it contains
        azure_rm_resourcegroup_info:
        register: rg_info

      - name: Find Resource Groups Name
        set_fact:
          rg_name: "{{ rg_info | json_query(query) }}"
        vars:
          query: "resourcegroups[?name.contains(@, '{{ rg_name_regex }}' )].name"

      - name: Debug
        debug:
          var: rg_name

      - name: Find NICs in the Resource Group
        azure_rm_virtualmachinescaleset_info:
          resource_group: "{{ rg_name }}"
        register: rg_vmss_info

      - name: Debug
        debug:
          var: rg_vmss_info
